name: Social Service CI/CD

on:
  push:
    paths:
      - 'Social-Service/**'      # only triggers if any file in auth-service changes
  pull_request:
    paths:
      - 'Social-Service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 25
      uses: actions/setup-java@v3
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Build Social Service
      run: mvn -f Social-Service/pom.xml clean install
