name: Social Service CI/CD

on:
  push:
    paths:
      - 'Social-Service/**'      # only triggers if any file in auth-service changes
  pull_request:
    paths:
      - 'Social-Service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 25
      uses: actions/setup-java@v3
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Build Social Service
      run: mvn -f Social-Service/pom.xml clean install

    - name: Run Tests
      run: mvn -f Social-Service/pom.xml test

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('Social-Service/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f Social-Service/pom.xml -Dsonar.projectKey=DionNuijens_Media-Connect-SocialService


    - name: Build JAR with Maven
      run: mvn -f Social-Service/pom.xml clean package -DskipTests

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./Social-Service
        file: ./Social-Service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/social-service:latest
